"""add_goals_and_journal_tables

Revision ID: 0184ea910800
Revises: a37388c9e015
Create Date: 2025-11-15 08:03:54.314224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '0184ea910800'
down_revision: Union[str, Sequence[str], None] = 'a37388c9e015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns already exist (for idempotency)
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Get existing columns for peer_benchmarks table
    if 'peer_benchmarks' in inspector.get_table_names():
        existing_columns = [col['name'] for col in inspector.get_columns('peer_benchmarks')]
    else:
        existing_columns = []
    
    # Get existing columns for journal_entries table
    if 'journal_entries' in inspector.get_table_names():
        journal_columns = [col['name'] for col in inspector.get_columns('journal_entries')]
    else:
        journal_columns = []
    
    # Alter journal_entries.prompt if table and column exist
    if 'journal_entries' in inspector.get_table_names() and 'prompt' in journal_columns:
        try:
            op.alter_column('journal_entries', 'prompt',
                       existing_type=sa.VARCHAR(length=200),
                       type_=sa.String(length=500),
                       existing_nullable=True)
        except Exception:
            pass  # Column might already be the correct type
    
    # Add new columns if they don't exist
    if 'avg_readiness_score' not in existing_columns:
        op.add_column('peer_benchmarks', sa.Column('avg_readiness_score', sa.Float(), nullable=False))
    if 'avg_technical_score' not in existing_columns:
        op.add_column('peer_benchmarks', sa.Column('avg_technical_score', sa.Float(), nullable=False))
    if 'avg_soft_skills_score' not in existing_columns:
        op.add_column('peer_benchmarks', sa.Column('avg_soft_skills_score', sa.Float(), nullable=False))
    if 'avg_leadership_score' not in existing_columns:
        op.add_column('peer_benchmarks', sa.Column('avg_leadership_score', sa.Float(), nullable=False))
    if 'median_readiness_score' not in existing_columns:
        op.add_column('peer_benchmarks', sa.Column('median_readiness_score', sa.Float(), nullable=False))
    
    # Alter columns if they exist
    if 'specialization_id' in existing_columns:
        try:
            op.alter_column('peer_benchmarks', 'specialization_id',
                       existing_type=sa.INTEGER(),
                       nullable=False)
        except Exception:
            pass
    if 'total_users' in existing_columns:
        try:
            op.alter_column('peer_benchmarks', 'total_users',
                       existing_type=sa.INTEGER(),
                       nullable=False)
        except Exception:
            pass
    if 'last_updated' in existing_columns:
        try:
            op.alter_column('peer_benchmarks', 'last_updated',
                       existing_type=postgresql.TIMESTAMP(),
                       type_=sa.DateTime(timezone=True),
                       existing_nullable=True)
        except Exception:
            pass
    
    # Drop old columns if they exist
    if 'avg_leadership' in existing_columns:
        op.drop_column('peer_benchmarks', 'avg_leadership')
    if 'avg_technical' in existing_columns:
        op.drop_column('peer_benchmarks', 'avg_technical')
    if 'avg_readiness' in existing_columns:
        op.drop_column('peer_benchmarks', 'avg_readiness')
    if 'median_readiness' in existing_columns:
        op.drop_column('peer_benchmarks', 'median_readiness')
    if 'avg_soft_skills' in existing_columns:
        op.drop_column('peer_benchmarks', 'avg_soft_skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peer_benchmarks', sa.Column('avg_soft_skills', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('peer_benchmarks', sa.Column('median_readiness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('peer_benchmarks', sa.Column('avg_readiness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('peer_benchmarks', sa.Column('avg_technical', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('peer_benchmarks', sa.Column('avg_leadership', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('peer_benchmarks', 'last_updated',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('peer_benchmarks', 'total_users',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('peer_benchmarks', 'specialization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('peer_benchmarks', 'median_readiness_score')
    op.drop_column('peer_benchmarks', 'avg_leadership_score')
    op.drop_column('peer_benchmarks', 'avg_soft_skills_score')
    op.drop_column('peer_benchmarks', 'avg_technical_score')
    op.drop_column('peer_benchmarks', 'avg_readiness_score')
    op.alter_column('journal_entries', 'prompt',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
